### ISSUE TITLE
Example project link broken

### ISSUE THREAD

**Issue by gizm00** [stencila/website#71] opened 2018-07-17 15:36 UTC
Hey there - I searched the issues and didnt see something on this already, so apologies if I missed an existing issue.

I was trying to run through your [quick start page](https://stenci.la/learn/quick-start.html) and the link for the example project results in a 404, it links to https://stenci.la/learn/rodents.dar.zip

This looks like a really cool project! I work on a team building a DMS for clinical trials and someone in our department shared stencila in slack yesterday. 👍

**Comment by apawlik** [comment] 2018-07-17 21:52
Ouch! Thank you for reporting this @gizm00 ! I am on it to fix it.

**Comment by apawlik** [comment] 2018-07-17 21:56
OK, I see what the problem is: if you click directly on the link it tries download the file:

![image](https://user-images.githubusercontent.com/2358535/42847660-bc8114be-8a70-11e8-963e-54f4d2528ec2.png)

But if you right click on it and open in new tab it gives you 404. 
I will try to sort that out but for now @gizm00  if you would like to download the `zip` just left-click it.

**Comment by apawlik** [comment] 2018-07-17 22:01
Fixed by https://github.com/stencila/website/pull/72

**Closed by apawlik** 2018-07-17 22:01 UTC

**Comment by gizm00** [comment] 2018-07-19 20:41
Thanks!
